# Description: Makefile for downloading assets
default: disney

#Source: mp4
disney:
	wget -O disney.webm https://upload.wikimedia.org/wikipedia/en/transcoded/8/83/Walt_Disney_Pictures_Logo_as_of_2022.ogv/Walt_Disney_Pictures_Logo_as_of_2022.ogv.1080p.vp9.webm

mary:
	# From the Mary Project: https://www.meryproject.com/
	# 360 Stereo from http://pedrofe.com/rendering-for-oculus-rift-with-arnold/
	wget -O mary.webm https://threejs.org/examples/textures/MaryOculus.webm